### PR TITLE
offroad: Add color corrections button using intent

### PR DESCRIPTION
**Pull request by ihsakashi**

### CODE REVIEW

**Comment by brianandyt** [comment]
This is color blind mode comma just shut down

**Comment by ihsakashi** [comment]
https://github.com/ihsakashi/openpilot-apks/commit/e3d2e152050ca368f41942120914eb8741976033

**Comment by ShaneSmiskol** [comment]
Is this draft ready for review?

**Comment by ihsakashi** [comment]
Yes

**Comment by ShaneSmiskol** [comment]
Thanks for the PR!

**Pull request merged**
