### PR TITLE
Corolla TSS2 Tune

### PR DESCRIPTION
**Pull request by majorwolf**
Add birdman6450#7399's Tune for Corolla TSS2.

### CODE REVIEW

**Comment by ShaneSmiskol** [comment]
Can you try to add a parameter with opParams for the TSS2 Corolla? You can enable the new tune by default, check out how I did it for Corolla and Prius

**Comment by majorwolf** [comment]
Added to opParams, I set it to false by default unless you think it should be set to True.

**Comment by ShaneSmiskol** [comment]
Thanks! I'll check it out tomorrow when I get home

**Comment by ShaneSmiskol** [comment]
thanks for the PR! merged

**Pull request merged**
