### PR TITLE
PRIUS_TSS2 and adjust DF with Toyota's steering distance button (TSS2 only).

### PR DESCRIPTION
**Pull request by rav4kumar**
https://streamable.com/seibys

### CODE REVIEW

**Comment by aronasorman** [comment]
Nice! I was looking to add this feature myself. Were there any other blockers for this?

**Comment by aronasorman** [comment]
Tested this PR and it's working pretty well on my 2021 Prius Prime. One small bug is that the distance change triggers quite often when i disengage. Either by pressing the ACC button or stepping on the gas/brake.

**Comment by aronasorman** [comment]
Said small bug now became major.

When I activate ACC, my car now says that LTA is malfunctioning, and after a second or so my C2 will say that controls are unresponsive.

There may be something specific to 2021 Priuses that's causing a malfunction issue. I'll see if I can look further into this!

**Comment by rav4kumar** [comment]
> Said small bug now became major.
> 
> When I activate ACC, my car now says that LTA is malfunctioning, and after a second or so my C2 will say that controls are unresponsive.
> 
> There may be something specific to 2021 Priuses that's causing a malfunction issue. I'll see if I can look further into this!

@ShaneSmiskol can you provide me with that crashlog.

**Comment by aronasorman** [comment]
Here's what I get @rav4kumar :
```
root@localhost:/data/openpilot$ cat /data/community/crashes/16-02-2021--07\:51.15-AM.log
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/launcher.py", line 20, in launcher
    mod.main()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 657, in main
    controls.controlsd_thread()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 651, in controlsd_thread
    self.step()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 641, in step
    actuators, v_acc, a_acc, lac_log = self.state_control(CS)
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 457, in state_control
    actuators.steer, actuators.steerAngle, lac_log = self.LaC.update(self.active, CS, self.CP, path_plan)
  File "/data/openpilot/selfdrive/controls/lib/latcontrol_pid.py", line 46, in update
    output_steer = self.pid.update(self.angle_steers_des, CS.steeringAngle, check_saturation=check_saturation, override=CS.steeringPressed,
  File "/data/openpilot/selfdrive/controls/lib/pid.py", line 71, in update
    self.p = error * self.k_p
  File "/data/openpilot/selfdrive/controls/lib/pid.py", line 36, in k_p
    return interp(self.speed, self._k_p[0], self._k_p[1])
  File "/data/openpilot/common/numpy_fast.py", line 19, in interp
    return [get_interp(v) for v in x] if hasattr(x, '__iter__') else get_interp(x)
  File "/data/openpilot/common/numpy_fast.py", line 15, in get_interp
    return fp[-1] if hi == N and xv > xp[low] else (
  File "capnp/lib/capnp.pyx", line 497, in capnp.lib.capnp._DynamicListBuilder.__getitem__
ZeroDivisionError: integer division or modulo by zero
```

**Comment by ShadowVlican** [comment]
would be great if this worked on the corolla hatchback 2019+ too (also TSS2)

**Comment by rav4kumar** [comment]
it should!
ill do updated version soon with latest SA

**Comment by PhiltorX** [comment]
I'm very new to this. I'm currently running Shane's laneless branch on my C2, how can I implement this on my 2021 Prius Prime Limited?

**Pull request closed without merging**
